sudo: true
language: node_js
node_js:
- '6'
script:
- cd generator
- npm install
- bash ./distribute.sh
env:
  global:
  - secure: jvyzM8qmQeET1n4314w4g1N6il+taBEdC8LgFw5tJvcVQrZ3q08Pr1JEsbb3vPvFwZXQwrr++kDPBk3milBJrKf93woVv3sNYK2TPNzIDsfZBOryXtq4AHf6LSL3DNqvjX+sQxW6j+SLltS82WWS8pXQaVIZxfl5yEYqmkiGTHMKPE/WfSDErg9hRsQrRn51ND/pXjSSjfyvjqbjwvEkqMfBdRfmCLS4x98Ivs7N830HlBbjXoMPSw/+JFROZXDq4j+1j6czTUo3IiN5fV7+3+5xYIZZJo5jRNXHnzD/FFR71dDqgo1NhMCN/7IHjIoEIYBUGfn7fAMLlGjb+1ZzL83GNh4h8i5w033f4b3+jL/DXdZnpAHD3L4c+KHFsDOd0PvZ9Td3t114bAv59Fcv7O298gUaxKdxCJC3BW5TZRqU15WgHfQGX8unl68A+9Iu3w8VuXSXZpoTfwQpmsO5yOF+EEyeDAAN7Mu8VDCsMSUGeUXTUyraKtsvNjG56YbGAXL0Egrp3cd2U086uJyvBUYJjR9hUMh/7rm6mcZ1sUN3oCLX+er5xKoYZhgWcpDgLdubpuxeFxN9+szndexa/XRT7dEfu0woMZra1eaeRMpL5u6qbEuUHqHzOsT8m/DAIn3Jp2IXYnLRalDnc0VgFpAvr0i4y1w2qYAEPU+Mlv4=
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install git -y
  - git --version